Repository mrbeam/MrBeamPlugin, pull requests merged in 2021-02, with the labels that each got.

#1141 Adds more device data to a user review (#1137)
  octoprint_mrbeam/analytics/review_handler.py
  octoprint_mrbeam/static/js/review.js
Labels: enhancement

#1161 B working area helper scope
  octoprint_mrbeam/static/js/helpers/working_area_helper.js
  octoprint_mrbeam/templates/tab_workingarea.jinja2
Labels: bug

#1173 Fix user permissions for calibration and clean left over files.
  octoprint_mrbeam/__init__.py
  octoprint_mrbeam/camera/lens.py
  octoprint_mrbeam/iobeam/lid_handler.py
  octoprint_mrbeam/util/flask.py
Labels: bug, camera
